---
- name: deployment k8s master
  command: ovftool 
    --X:injectOvfEnv
    --X:logFile=ovftool.log 
    --allowExtraConfig
    --acceptAllEulas 
    --noSSLVerify
    --powerOn
    --datastore={{vc.ds}}
    --net:64-0={{k8mgmt.lswname}}
    --net:65-0={{k8overlay.lswname}}
    --name={{k8master.name}}
    --prop:hostname={{k8master.name}}
    --prop:ip={{k8master.ip}}
    --prop:netmask={{k8common.netmask}}
    --prop:gateway={{k8common.gw}}
    --prop:dns={{k8common.dns}}
    {{k8image.template}}   
    vi://{{vc.user}}:{{vc.pass}}@{{vc.server}}/{{vc.dc}}/host/{{vc.comp_cluster}}

- name: deployment container host1
  command: ovftool
    --X:injectOvfEnv
    --X:logFile=ovftool.log
    --allowExtraConfig
    --acceptAllEulas
    --noSSLVerify
    --powerOn
    --datastore={{vc.ds}}
    --net:64-0={{k8mgmt.lswname}}
    --net:65-0={{k8overlay.lswname}}
    --name={{k8node1.name}}
    --prop:hostname={{k8node1.name}}
    --prop:ip={{k8node1.ip}}
    --prop:netmask={{k8common.netmask}}
    --prop:gateway={{k8common.gw}}
    --prop:dns={{k8common.dns}}
    {{k8image.template}}
    vi://{{vc.user}}:{{vc.pass}}@{{vc.server}}/{{vc.dc}}/host/{{vc.comp_cluster}}

- name: deployment container host2
  command: ovftool
    --X:injectOvfEnv
    --X:logFile=ovftool.log
    --allowExtraConfig
    --acceptAllEulas
    --noSSLVerify
    --powerOn
    --datastore={{vc.ds}}
    --net:64-0={{k8mgmt.lswname}}
    --net:65-0={{k8overlay.lswname}}
    --name={{k8node2.name}}
    --prop:hostname={{k8node2.name}}
    --prop:ip={{k8node2.ip}}
    --prop:netmask={{k8common.netmask}}
    --prop:gateway={{k8common.gw}}
    --prop:dns={{k8common.dns}}
    {{k8image.template}}
    vi://{{vc.user}}:{{vc.pass}}@{{vc.server}}/{{vc.dc}}/host/{{vc.comp_cluster}}

- pause:
    minutes: 1

#- pause: 
#    prompt: Before vCenter 6.5U2, ovftool hits bug to attach vnic to NSX logical switch, you need rewire vnic into overlay switch manually. Once you done, press enter to continue.
